name: Unit Tests

on:
  push:
  pull_request:

jobs:
  build-test:
    strategy:
      matrix:
        php-version: [ "8.0", "8.1", "8.2" ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install composer and dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}

      - uses: php-actions/phpstan@v3
        with:
          version: composer
          php_version: ${{ matrix.php-version }}
          configuration: phpstan.neon

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          php_version: ${{ matrix.php-version }}
          bootstrap: test/bootstrap.php
          testsuite: Test Suite
          configuration: phpunit.xml
          php_extensions: xdebug
          args: test --coverage-clover ./coverage.xml

      -
        if: ${{ matrix.php-version == '8.2' }}
        name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./coverage.xml
          verbose: true